!ArenaConfig
arenas:
  0: !Arena # CWC-F
    pass_mark: 0
    t: 250
    items:
    - !Item
      name: Agent
      rotations: [0]
      positions:
      - !Vector3 {x: 20, y: 5, z: 20}
    - !Item
      name: Wall # platform
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
      rotations: [0]
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      sizes:
      - !Vector3 {x: 5, y: 5, z: 1}
    - !Item
      name: Cardbox1 # left cardbox
      positions:
      - !Vector3 {x: 5, y: 0, z: 5}      
      - !Vector3 {x: 13.75, y: 0, z: 5}
      - !Vector3 {x: 5, y: 0, z: 15}      
      - !Vector3 {x: 13.75, y: 0, z: 15}
      - !Vector3 {x: 5, y: 0, z: 25}      
      - !Vector3 {x: 13.75, y: 0, z: 25}
      - !Vector3 {x: 5, y: 0, z: 35}      
      - !Vector3 {x: 13.75, y: 0, z: 35}
      rotations: [0,0,0,0,0,0,0,0]
      sizes:
      - !Vector3 {x: 10, y: 10, z: 10}
      - !Vector3 {x: 7.5, y: 10, z: 10}
      - !Vector3 {x: 10, y: 10, z: 10}
      - !Vector3 {x: 7.5, y: 10, z: 10}
      - !Vector3 {x: 10, y: 10, z: 10}
      - !Vector3 {x: 7.5, y: 10, z: 10}
      - !Vector3 {x: 10, y: 10, z: 10}
      - !Vector3 {x: 7.5, y: 10, z: 10}
    - !Item
      name: Cardbox1 # right cardbox
      positions:
      - !Vector3 {x: 35, y: 0, z: 5}      
      - !Vector3 {x: 26.25, y: 0, z: 5}
      - !Vector3 {x: 35, y: 0, z: 15}      
      - !Vector3 {x: 26.25, y: 0, z: 15}
      - !Vector3 {x: 35, y: 0, z: 25}      
      - !Vector3 {x: 26.25, y: 0, z: 25}
      - !Vector3 {x: 35, y: 0, z: 35}      
      - !Vector3 {x: 26.25, y: 0, z: 35}
      rotations: [0,0,0,0,0,0,0,0]
      sizes:
      - !Vector3 {x: 10, y: 10, z: 10}
      - !Vector3 {x: 7.5, y: 10, z: 10}
      - !Vector3 {x: 10, y: 10, z: 10}
      - !Vector3 {x: 7.5, y: 10, z: 10}
      - !Vector3 {x: 10, y: 10, z: 10}
      - !Vector3 {x: 7.5, y: 10, z: 10}
      - !Vector3 {x: 10, y: 10, z: 10}
      - !Vector3 {x: 7.5, y: 10, z: 10}
    - !Item
      name: GoodGoal # forward goal
      positions:
      - !Vector3 {x: 20, y: 0, z: 23}
      - !Vector3 {x: 20, y: 0, z: 27}
      sizes:
      - !Vector3 {x: 4, y: 4, z: 4}
      - !Vector3 {x: 4, y: 4, z: 4}
    - !Item
      name: DeathZone # backward death
      positions:
      - !Vector3 {x: 20, y: 0, z: 9.75}
      rotations: [0]
      sizes:
      - !Vector3 {x: 5, y: 10, z: 19.5}
    - !Item # forward wall
      name: Wall
      rotations: [0]
      positions:
      - !Vector3 {x: 20, y: 0, z: 39}
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      sizes:
      - !Vector3 {x: 5, y: 10, z: 1}